import React, { createContext, useState, useContext } from "react";

const translations = {
  vi: {
    adminDashboard: "Dashboard",
    employees: "Nhân Sự",
    insertData: "Thêm Dữ Liệu",
    workSchedule: "Cài Đặt Thời Gian",
    welcome: "Chào mừng đến với Bảng Điều Khiển",
    selectTab: "Chọn một tab từ thanh bên để bắt đầu.",
    loading: "Đang tải...",
    // EmployeeList
    employeeList: "Danh Sách Nhân Sự",
    code: "Mã Nhân Sự",
    name: "Họ Tên",
    position: "Vị Trí",
    salary: "Lương",
    status: "Trạng Thái",
    actions: "Hành Động",
    noEmployees: "Không tìm thấy nhân sự",
    confirmDelete: `Bạn có chắc chắn muốn xóa nhân sự này không? \nHành động này sẽ xóa toàn bộ thiết bị và dữ liệu điểm danh liên quan.`,
    deleteSuccess: "Đã xóa nhân sự thành công.",
    deleteError: "Lỗi khi xóa nhân sự.",
    editEmployee: "Sửa Thông Tin NV",
    updateSuccess: "Cập nhật nhân sự thành công!",
    updateError: "Cập nhật thất bại.",
    updateButton: "Cập nhật",
    // EmployeeDetails
    backToEmployees: "← Quay lại danh sách",
    attendanceHistory: "Lịch Sử Điểm Danh",
    hireDate: "Ngày vào làm",
    date: "Ngày",
    checkIn: "Giờ Vào",
    checkOut: "Giờ Ra",
    noAttendance: "Không tìm thấy dữ liệu điểm danh",
    profileImage: "Ảnh Đại Diện",
    profileInfo: "Thông Tin Cá Nhân",
    email: "Email",
    phoneNumber: "Số Điện Thoại",
    socialMedia: "Mạng Xã Hội",
    showAttendance: "Xem Lịch Sử Điểm Danh",
    hideAttendance: "Quay trở lại",
    monthFilter: "Lọc theo tháng",
    allMonths: "Tất cả các tháng",
    sun: "CN",
    mon: "T2",
    tue: "T3",
    wed: "T4",
    thu: "T5",
    fri: "T6",
    sat: "T7",
    // InsertData
    insertEmployeeDevice: "Thêm Nhân Sự & Thiết Bị",
    employeeDetails: "Thông Tin Nhân Sự",
    deviceDetails: "Thông Tin Thiết Bị",
    dob: "Ngày Sinh",
    deviceName: "Tên Thiết Bị (VD: PC-01)",
    macAddress: "Địa chỉ MAC",
    inserting: "Đang thêm...",
    insertButton: "Thêm Dữ Liệu",
    macExists: "Địa chỉ MAC này đã được đăng ký cho thiết bị khác.",
    insertSuccess: "Thêm nhân sự và thiết bị thành công!",
    insertError: "Đã xảy ra lỗi khi thêm dữ liệu.",
    profileImageUpload: "Tải Lên Ảnh Đại Diện",
    active: "Đang làm việc",
    inactive: "Đã nghỉ việc",
    // WorkSchedule
    manageSchedule: "Quản Lý Lịch Làm Việc",
    dayType: "Loại Ngày Làm Việc",
    weekday: "Trong tuần",
    weekend: "Cuối tuần",
    startTime: "Giờ Bắt Đầu",
    endTime: "Giờ Kết Thúc",
    lateThreshold: "Cho Phép Đi Trễ (Phút)",
    effectiveFrom: "Áp Dụng Từ Ngày (Tuỳ chọn)",
    effectiveTo: "Áp Dụng Đến Ngày (Tuỳ chọn)",
    saving: "Đang lưu...",
    saveSchedule: "Lưu Lịch",
    currentSchedules: "Lịch Làm Việc Hiện Tại",
    lateMins: "Trễ (phút)",
    noSchedules: "Chưa có lịch làm việc",
    scheduleSuccess: "Lưu lịch làm việc thành công!",
    scheduleError: "Lỗi khi lưu lịch làm việc.",
    // DailyAttendance
    dailyAttendance: "Thông Báo Điểm Danh",
    selectDate: "Chọn Ngày",
    searchDate: "Xem Điểm Danh",
    attendanceStatus: "Trạng Thái Điểm Danh",
    checkInTime: "Giờ Vào",
    checkOutTime: "Giờ Ra",
    lateMinutes: "Đi Trễ (phút)",
    present: "Đầy Đủ",
    absent: "Vắng Mặt",
    onTime: "Đúng Giờ",
    late: "Đi Trễ",
    leaveEarly: "Nghỉ sớm",
    notCheckedOut: "Chưa Check-out",
    summary: "Thống Kê",
    note: "Ghi chú",
    saveNote: "Lưu",
    noteSuccess: "Đã lưu ghi chú!",
    noteError: "Lỗi khi lưu ghi chú",
    dayNotSelected: "Vui lòng chọn ngày",
    noDataForNote: "Không có dữ liệu điểm danh ngày này",
  },
  en: {
    adminDashboard: "Dashboard",
    employees: "Employees",
    insertData: "Insert Data",
    workSchedule: "Work Schedule",
    welcome: "Welcome to the Admin Dashboard",
    selectTab: "Select a tab from the sidebar to begin.",
    loading: "Loading...",
    // EmployeeList
    employeeList: "Employee List",
    code: "Code",
    name: "Name",
    position: "Position",
    salary: "Salary",
    status: "Status",
    actions: "Actions",
    noEmployees: "No employees found",
    confirmDelete:
      "Are you sure you want to delete this employee? This will also delete all associated devices and attendance records.",
    deleteSuccess: "Employee deleted successfully.",
    deleteError: "Error deleting employee.",
    editEmployee: "Edit Employee",
    updateSuccess: "Employee updated successfully!",
    updateError: "Update failed.",
    updateButton: "Update",
    // EmployeeDetails
    backToEmployees: "← Back to Employees",
    attendanceHistory: "Attendance History",
    hireDate: "Hire Date",
    date: "Date",
    checkIn: "Check In",
    checkOut: "Check Out",
    noAttendance: "No attendance records found",
    profileImage: "Profile Image",
    profileInfo: "Profile Information",
    email: "Email",
    phoneNumber: "Phone Number",
    socialMedia: "Social Media Links",
    showAttendance: "Show Attendance History",
    hideAttendance: "Hide Attendance",
    monthFilter: "Filter by month",
    allMonths: "All Months",
    sun: "Su",
    mon: "Mo",
    tue: "Tu",
    wed: "We",
    thu: "Th",
    fri: "Fr",
    sat: "Sa",
    // InsertData
    insertEmployeeDevice: "Insert Employee & Device Data",
    employeeDetails: "Employee Details",
    deviceDetails: "Device Details",
    dob: "Date of Birth",
    deviceName: "Device Name (e.g. PC-01)",
    macAddress: "MAC Address",
    deviceActive: "Device Active?",
    inserting: "Inserting...",
    insertButton: "Insert Data",
    macExists: "This MAC address is already registered to another device.",
    insertSuccess: "Employee and device data inserted successfully!",
    insertError: "An error occurred during insertion.",
    profileImageUpload: "Upload Profile Image",
    active: "Active",
    inactive: "Inactive",
    // WorkSchedule
    manageSchedule: "Manage Work Schedule",
    dayType: "Work Day Type",
    weekday: "Weekday (in_week)",
    weekend: "Weekend (weekend)",
    startTime: "Start Time (HH:MM:SS)",
    endTime: "End Time (HH:MM:SS)",
    lateThreshold: "Late Threshold (Minutes)",
    effectiveFrom: "Effective From (Optional)",
    effectiveTo: "Effective To (Optional)",
    saving: "Saving...",
    saveSchedule: "Save Schedule",
    currentSchedules: "Current Schedules",
    lateMins: "Late (mins)",
    noSchedules: "No schedules found",
    scheduleSuccess: "Work schedule saved successfully!",
    scheduleError: "Error saving work schedule.",
    // DailyAttendance
    dailyAttendance: "Daily Attendance",
    selectDate: "Select Date",
    searchDate: "View Attendance",
    attendanceStatus: "Attendance Status",
    checkInTime: "Check In Time",
    checkOutTime: "Check Out Time",
    lateMinutes: "Late (mins)",
    present: "Present",
    absent: "Absent",
    onTime: "On Time",
    late: "Late",
    leaveEarly: "Leave Early",
    notCheckedOut: "Not Checked Out",
    summary: "Summary",
    note: "Note",
    saveNote: "Save Note",
    noteSuccess: "Note saved successfully!",
    noteError: "Error saving note",
    dayNotSelected: "Please select a day",
    noDataForNote: "No attendance data for this day",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("vi"); // Default to Vietnamese

  const t = (key) => {
    return translations[lang][key] || key;
  };

  const toggleLanguage = () => {
    setLang((prev) => (prev === "vi" ? "en" : "vi"));
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
